from __future__ import annotations

from pydantic import BaseModel, Field


class StartSessionRequest(BaseModel):
    message: str = Field(min_length=1)
    user_id: str | None = None
    preselected_bundle_key: str | None = Field(
        default=None,
        description=(
            "Optional. Skip AI classification and use this bundle key directly. "
            "Must match a key in the bundle registry. "
            "Returns HTTP 400 for unknown keys."
        ),
    )
    preselected_intent: str | None = Field(
        default=None,
        description=(
            "Optional. A known intent string from the bundle registry "
            "(e.g. 'manage employees') "
            "to guide classification and boost matching bundles. "
            "Returns HTTP 400 for unrecognised intents. "
            "Persisted across all turns of the session."
        ),
    )


class ReplyRequest(BaseModel):
    message: str = Field(min_length=1)
    force_preview: bool = Field(
        default=False,
        description=(
            "Optional. If true, immediately returns a preview with the "
            "best available bundle "
            "without requiring missing-field completion or bundle confirmation. "
            "The response will include a warning and preview_type='early'."
        ),
    )


class ConfirmBundleRequest(BaseModel):
    confirmed: bool


class GenerateAppRequest(BaseModel):
    """Request schema for finalizing and packaging the app payload.

    Expects the personalized dummy_data_json generated during the preview step.
    """

    dummy_data_json: dict[str, object] = Field(
        ...,
        description=(
            "The personalized sample data generated by the preview generator. "
            "Must include 'bundle_key' and 'stores'."
        ),
    )
    generation_json: dict[str, object] | None = Field(
        default=None,
        description=(
            "Optional. Preview generation_json payload from the client. "
            "When provided, /sessions/{id}/app validates and packages this "
            "payload instead of loading static app.json."
        ),
    )
    v2_manifest: dict[str, object] | None = Field(
        default=None,
        description=(
            "Optional. V2 tenant provisioning manifest produced by the preview pipeline. "
            "When provided, /sessions/{id}/app validates and packages this manifest "
            "as the primary response payload. Old clients that omit this field are "
            "unaffected — default is None."
        ),
    )
